config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

get "tasks", to: "tasks#index"

get "tasks/new", to: "tasks#new"
post "tasks", to: "tasks#create" 

get "tasks/:id", to: "tasks#show", as: "task"

get "tasks/:id/edit", to: "tasks#edit", as: "tasks_edit"
patch "tasks/:id", to: "tasks#update"

delete "tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task.id)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task.id)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end


  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1><strong>New task</strong></h1>
<div>
  <%= form_for @task do |f| %>
  <p>
    <%= f.label :title  %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :details  %>
    <%= f.text_field :details %>
  </p>
  <p>
    <label>
        <%= f.check_box :completed %> Completed
    </label>
  </p>
  <p>
    <%= f.submit class: 'btn btn-primary'%>
    <% end %>
  </p>
</div>
  
<%= link_to "Back to list", tasks_path %>

app/views/tasks/index.html.erb
<h1><strong>My tasks</strong></h1>

<ul class="checkbox">
  <% @tasks.each do |task| %>
    <li>
      <% if task.completed %>
        <%# <%= check_box_tag (:checkbox) %> 
        <%# <%= link_to task.title, task_path(task.id) %> 
        <i class="fa fa-check-square-o"></i>
      <% else %>
        <i class="fa fa-square-o"></i>   
        <% end %>
        <%= link_to task.title, task_path(task.id) %>
        <%= link_to task_path(task.id), method: :delete, data: { confirm: "Delete #{task.title}?" } do%>
          <i class="fa fa-trash-o" aria-hidden="true"></i>
      <% end %>
    </li>
  <% end %>
</ul>

<%= link_to tasks_new_path do %>
  <i class="fa fa-plus">Add a new task</i>
<% end %>

app/views/tasks/new.html.erb
<h1><strong>New task</strong></h1>
<div class="form">
  <%= form_for @task do |f| %>
  <p>
    <%= f.label :title  %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :details  %>
    <%= f.text_field :details %>
  </p>
  <p>
    <%= f.submit "Create Task" %>
    <% end %>
  </p>
</div>
  
<%= link_to "Back to list", tasks_path %>

app/views/tasks/show.html.erb
<h1><strong><%= @task.title %></strong></h1>
<p><%= @task.details %></p>

<% if @task.completed %>
  <i class="fa fa-check-square-o"></i> This task is completed
<% else %>
  <i class="fa fa-square-o"></i> This task is not completed yet
<% end %>
<br>


<%= link_to "Edit task", tasks_edit_path %><br>


<%= link_to "Back to list", tasks_path %>